const choachesList = [
	{
		id:1,
		name: "Coach Smith",
		age: 40,
		city: "New York",
		yearsExperience: 15,
		certificationLevel: "Level 4",
		specialization: "Butterfly",
		competitionsTrained: "Regional",
		coachingStyle: "Technical",
		availability: "Full-time",
		rating: 5,
		references: ["Swim Team A", "Swim Team B"],
		coachingAwards: ["Coaching Award 1", "Coaching Award 2"],
		mentoringExperience: 8,
		knowledgeOfSportsPsychology: true,
		familiarityWithCoachingTools: true,
		abilityToProvideFeedback: true,
		experienceInCreatingTrainingPlans: true,
		knowledgeOfSwimmerNutrition: true,
		familiarityWithInjuryPrevention: true,
		swimmingTypesKnown: 4,
		reviews: 25,
		experienceDescription:
			"Coach Smith is a seasoned swimming coach with 15 years of experience. He specializes in coaching the butterfly stroke and has trained swimmers at the regional level. His coaching style is technical and he has received several coaching awards for his contributions to the sport.",
		swimmingTypes: [
			"freestyle",
			"backstroke",
			"breaststroke",
			"butterfly",
			"diving",
		],
	},
	{
		id:2,
		name: "Coach Johnson",
		age: 35,
		city: "Los Angeles",
		yearsExperience: 12,
		certificationLevel: "Level 3",
		specialization: "Freestyle",
		competitionsTrained: "National",
		coachingStyle: "Motivational",
		availability: "Part-time",
		rating: 4,
		references: ["Swim Team C", "Swim Team D"],
		coachingAwards: ["Coaching Award 3", "Coaching Award 4"],
		mentoringExperience: 5,
		knowledgeOfSportsPsychology: true,
		familiarityWithCoachingTools: true,
		abilityToProvideFeedback: true,
		experienceInCreatingTrainingPlans: true,
		knowledgeOfSwimmerNutrition: true,
		familiarityWithInjuryPrevention: true,
		swimmingTypesKnown: 5,
		reviews: 19,
		experienceDescription:
			"Coach Johnson has 12 years of experience coaching swimmers in freestyle and other strokes at the national level. He is known for his motivational coaching style and has mentored several swimmers to success.",
		swimmingTypes: [
			"freestyle",
			"backstroke",
			"breaststroke",
			"butterfly",
			"sidestroke",
		],
	},
	{
		id:3,
		name: "Coach Garcia",
		age: 45,
		city: "Miami",
		yearsExperience: 20,
		certificationLevel: "Level 5",
		specialization: "Backstroke",
		competitionsTrained: "International",
		coachingStyle: "Intense",
		availability: "Full-time",
		rating: 4.5,
		references: ["Swim Team E", "Swim Team F"],
		coachingAwards: ["Coaching Award 5", "Coaching Award 6"],
		mentoringExperience: 10,
		knowledgeOfSportsPsychology: true,
		familiarityWithCoachingTools: true,
		abilityToProvideFeedback: true,
		experienceInCreatingTrainingPlans: true,
		knowledgeOfSwimmerNutrition: true,
		familiarityWithInjuryPrevention: true,
		swimmingTypesKnown: 5,
		reviews: 17,
		experienceDescription:
			"Coach Garcia brings 20 years of coaching experience to the table, specializing in backstroke and training swimmers at the international level. His coaching style is intense, and he has a strong track record of mentoring successful swimmers.",
		swimmingTypes: [
			"freestyle",
			"backstroke",
			"breaststroke",
			"butterfly",
			"diving",
		],
	},
];

export default choachesList;

